aws_region         = "us-west-1"
vpc_cidr           = "10.1.0.0/16"
public_subnet_cidr = "10.1.1.0/24"
private_app_cidr   = "10.1.2.0/24"
private_db_cidr    = "10.1.5.0/24"
environment        = "qa"
instance_type      = "t3.medium"
rds_username       = "admin"
create_iam_role    = true
rds_password       = "StgSecretPassword123!"
ami_id            = "ami-05d3fca72a856bc63"  # Replace with region-specific Amazon Linux 2 AMI
key_name           = "stg"
